apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: elastic-search
  name: elastic-search
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    io.kompose.service: elastic-search
status:
  loadBalancer: {}
