apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-new.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/tap: "true"
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: STREAMING_PORT
              value: "6001"
            - name: TCP_PORT
              value: "6000"
            - name: TOPIC
              value: amazon
          image: federicocanzonieri/amk-logstash
          name: logstash-am
          ports:
            - containerPort: 6000
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: task-logstash-storage
      restartPolicy: Always
      volumes:
        - name: task-logstash-storage
          persistentVolumeClaim:
            claimName: task-logstash-storage-claim
status: {}
