apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-logstash-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi