apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-logstash-storage	
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logstash-data"
