apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-new.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/tap: "true"
        io.kompose.service: zookeeper
    spec:
      containers:
        - env:
            - name: KAFKA_ACTION
              value: start-zk
          image: federicocanzonieri/amk-kafka
          name: zookeeper-am
          ports:
            - containerPort: 2181
          resources: {}
      restartPolicy: Always
status: {}
