apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  type: NodePort
  #type: LoadBalancer
  #loadBalancerIP: 20.86.151.143
  #externalIPs:
  #  - 20.86.151.143
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
      nodePort: 30008
  selector:
    io.kompose.service: kibana
