apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: elastic-search
  name: elastic-search
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic-search
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-new.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/tap: "true"
        io.kompose.service: elastic-search
    spec:
      hostname: elastic-search
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms2g -Xmx2g
            - name: discovery.type
              value: single-node
          image: federicocanzonieri/amk-elastic-search
          name: elastic-search-am
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: {}
      restartPolicy: Always
status: {}
