apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  type: NodePort
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30009
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
