apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-new.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/tap: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - image: federicocanzonieri/amk-kibana
          name: kibana-am
          ports:
            - containerPort: 5601
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/kibana/src/core/server/core_app/assets/favicons
              name: task-python-storage	
      restartPolicy: Always
      volumes:
        - name: task-python-storage	
          persistentVolumeClaim:
            claimName: task-python-storage-claim
status: {}
