apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-new.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/tap: "true"
        io.kompose.service: python
    spec:
      containers:
        - env:
            - name: CODE_PRODUCT
              value: B08SN9899W
            - name: DEBUG
              value: "yes"
            - name: DOMAIN_URL
              value: it
            - name: END_PAGE
              value: "6"
            - name: HOST_LOGSTASH
              value: 10.0.100.15
            - name: MODE_REVIEWS
              value: recent
            - name: PORT_LOGSTASH
              value: "6000"
            - name: PYTHON_APP
              value: amazonScraper.py
            - name: START_PAGE
              value: "0"
            - name: TIMEOUT_BEFORE_LOGSTASH
              value: "100"
            - name: TIMEOUT_BEFORE_SEND_TO_LOGSTASH
              value: "0"
            - name: TIMEOUT_FETCH_ANOTHER_PAGE
              value: "5"
            - name: AWS_ACCESS_KEY_ID
              value: "<TEMPLATE>"
            - name: AWS_SECRET_ACCESS_KEY
              value: "<TEMPLATE>"
            - name: BUCKET_NAME
              value: "federicobuckettest2021"
            - name: NAME_FILES_S3
              value: "Review_obt"
          image: federicocanzonieri/amk-python-s3
          name: python-am
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/images
              name: task-python-storage	
      restartPolicy: Always
      # hostNetwork: true
      # dnsPolicy: Default
      dnsConfig:
        nameservers:
          - 8.8.8.8
      volumes:
        - name: task-python-storage	
          persistentVolumeClaim:
            claimName: task-python-storage-claim

status: {}
