apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-new.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: python
  name: python
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-new.yml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.network/tap: "true"
        io.kompose.service: python
    spec:
      containers:
        - env:
            - name: CODE_PRODUCT
              valueFrom:
                secretKeyRef:
                  name: python-configuration
                  key: CODE_PRODUCT
            - name: DOMAIN_URL
              valueFrom:
                secretKeyRef:
                  name: python-configuration
                  key: DOMAIN_URL
            - name: MODE_REVIEWS
              valueFrom:
                secretKeyRef:
                  name: python-configuration
                  key: MODE_REVIEWS
            - name: START_PAGE
              valueFrom:
                secretKeyRef:
                  name: python-configuration
                  key: START_PAGE
            - name: END_PAGE
              valueFrom:
                secretKeyRef:
                  name: python-configuration
                  key: END_PAGE
            - name: TIMEOUT_FETCH_ANOTHER_PAGE
              valueFrom:
                secretKeyRef:
                  name: python-configuration
                  key: TIMEOUT_FETCH_ANOTHER_PAGE
            - name: DEBUG
              value: "yes"
            - name: HOST_LOGSTASH
              value: 10.0.100.15
            - name: PORT_LOGSTASH
              value: "6000"
            - name: PYTHON_APP
              value: amazonScraper.py
            - name: TIMEOUT_BEFORE_LOGSTASH
              value: "100"
            - name: TIMEOUT_BEFORE_SEND_TO_LOGSTASH
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: my-aws-credentials
                  key: BUCKET_NAME
            - name: NAME_FILES_S3
              valueFrom:
                secretKeyRef:
                  name: my-aws-credentials
                  key: NAME_FILES_S3
          
          # envFrom:
          # - secretRef:
          #     name: my-aws-credentials 

          image: federicocanzonieri/amk-python-s3
          name: python-am
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/images
              name: task-python-storage	
      restartPolicy: Always
      # hostNetwork: true
      # dnsPolicy: Default
      dnsConfig:
        nameservers:
          - 8.8.8.8
      volumes:
        - name: task-python-storage	
          persistentVolumeClaim:
            claimName: task-python-storage-claim

status: {}
