name: Publish Docker image

# Just for failing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_GITHUB_TOKEN: ${{ secrets.DOCKERHUB_USERNAME }}


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: test   
    defaults:
      run:
        working-directory: ./amk-s3/docker-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build-compose
        run: bash build-s3-opensearch.sh 
        
      - name: Rename images
        run: |
          docker tag amk-python-s3 ${{ secrets.DOCKERHUB_USERNAME }}/amk-python-s3-test-fin
          
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/amk-python-s3-test-fin

      - name: Get Private Key  
        run: |
              echo "${{ secrets.SSH_KEY }}" > ssh_dev_private_key
              chmod 600 ssh_dev_private_key
        
      - name: Do something on server
        run: ssh -i ssh_dev_private_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOSTNAME }} mkdir TESTCICD_ADESSO




      
          
        
        
        
