name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_GITHUB_TOKEN: ${{ secrets.DOCKERHUB_USERNAME }}
  TEST_SECRET: aonna
  IMAGE_NAME: alpine-test
  VERSION: 1.0.0

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./amk-s3/docker-image/python
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-cicd .
        
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-cicd
