name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_GITHUB_TOKEN: ${{ secrets.DOCKERHUB_USERNAME }}


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: test   
    defaults:
      run:
        working-directory: ./amk-s3/docker-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - run: ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build-compose
        run: bash build-s3-opensearch.sh 
      - name: Rename images
        run: |
          docker tag amk-python-s3 ${{ secrets.DOCKERHUB_USERNAME }}/amk-python-s3-test
          docker tag amk-spark-s3-to-s3 ${{ secrets.DOCKERHUB_USERNAME }}/amk-spark-s3-test
  #        docker tag amk-elastic-search ${{ secrets.DOCKERHUB_USERNAME }}/amk-elastic-search-test
 #         docker tag amk-kibana ${{ secrets.DOCKERHUB_USERNAME }}/amk-kibana-test
          docker tag amk-logstash-opensearch ${{ secrets.DOCKERHUB_USERNAME }}/amk-logstash-opensearch
          
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/amk-python-s3-test
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/amk-spark-s3-test
   #       docker push ${{ secrets.DOCKERHUB_USERNAME }}/amk-elastic-search-test
   #       docker push ${{ secrets.DOCKERHUB_USERNAME }}/amk-kibana-test
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/amk-logstash-opensearch


      
          
        
        
        
