name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_GITHUB_TOKEN: ${{ secrets.DOCKERHUB_USERNAME }}
  TEST_SECRET: aonna
  IMAGE_NAME: alpine-test
  VERSION: 1.0.0

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: test   
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - run: echo "Hello World" > file.txt
      - uses: actions/upload-artifact@v1
        with:
          name: file
          path: file.txt

      - name: Setup and run Dir tests
        working-directory: ./Algoritmi
        run: |
          ls

      - run: ls
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME} .
        
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}
